# Tensor 张量

## 1 深度学习基础概念 - 机器学习的两个基本问题

### 1.1 分类问题

分类问题的目标是预测一个离散的标签或类别。
这些标签通常是有限的，并且代表了不同的类别或组。

### 1.2 回归问题

回归问题的目标是预测一个连续的数值变量。
这些数值可以是无限的，回归模型尝试找到输入变量和连续输出变量之间的关系。


## 2 标量、向量、矩阵、张量

- 标量（Scalar）：0 阶张量
- 向量（Vector）：1 阶张量
- 矩阵（Matrix）：2 阶张量
- 张量（Tensor）：n 阶（Dimensions，维）


## 3 Tensor 的创建

### 3.1 创建特定值张量

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())


2.2.2
True


In [2]:
# 直接赋值初始化
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# 返回a的Tensor类型
print(a.type())
# 返回a的Tensor形状
print(a.shape)
# 创建指定形状的Tensor
b = torch.Tensor(2, 3)
print(b)
print(b.type())


torch.LongTensor
torch.Size([2, 3])
tensor([[1.2184e+24, 1.7082e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.FloatTensor


### 3.2 创建特殊值张量

In [3]:
print(f"全1张量：\n {torch.ones((2, 3, 4))}")
print(f"全0张量：\n {torch.zeros((2, 3, 4))}")
print(f"单位矩阵：\n {torch.eye(3)}")
print(f"指定大小张量：\n {torch.empty((2, 3, 4))}")
print(f"指定大小和值张量：\n {torch.full((2, 3, 4), 5)}")


全1张量：
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
全0张量：
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
单位矩阵：
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
指定大小张量：
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
指定大小和值张量：
 tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]])


In [4]:
# 拷贝自原属性（形状、数据类型）的新张量
x = torch.empty((2, 3, 4))
print(x)
print(f"拷贝全1张量：\n {torch.ones_like(x)}")
print(f"拷贝全0张量：\n {torch.zeros_like(x)}")
print(f"拷贝指定大小张量：\n {torch.empty_like(x)}")
print(f"拷贝指定大小和值张量：\n {torch.full_like(x, 5)}")


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
拷贝全1张量：
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
拷贝全0张量：
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
拷贝指定大小张量：
 tensor([[[1.2189e+24, 1.7082e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
拷贝指定大小和值张量：
 tensor([[[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]],

        [[5., 5., 5

### 3.3 随机初始化张量

In [5]:
print(f"随机张量∈(0, 1)：\n {torch.rand((2, 3, 4))}")
print(f"标准正态分布张量N(0, 1)，即固定随机序列平均值为0、标准差为1：\n {torch.randn((2, 3, 4))}")
print(f"正态分布张量，指定随机序列平均值为0.5、标准差为1.5：\n {torch.normal(0.5, 1.5, (2, 3, 4))}")
print(f"均匀分布张量，指定随机序列范围为(-5, 5)：\n {torch.Tensor(2, 3, 4).uniform_(-5, 5)}")


随机张量∈(0, 1)：
 tensor([[[0.8518, 0.5986, 0.7429, 0.8897],
         [0.8862, 0.9893, 0.9103, 0.3283],
         [0.6950, 0.9219, 0.4015, 0.4546]],

        [[0.0409, 0.1991, 0.1765, 0.2475],
         [0.6541, 0.9669, 0.7112, 0.9271],
         [0.2837, 0.9404, 0.1076, 0.5478]]])
标准正态分布张量N(0, 1)，即固定随机序列平均值为0、标准差为1：
 tensor([[[ 0.3483, -0.2772,  0.9988, -1.1597],
         [-1.1533, -0.1625,  0.6486,  0.7787],
         [-0.4750,  0.4442,  0.5001, -0.3844]],

        [[-0.4001, -0.1652, -0.8987, -0.5428],
         [ 1.3514, -0.3002, -0.4154,  0.6091],
         [-0.0984, -1.4002, -0.2479,  0.8838]]])
正态分布张量，指定随机序列平均值为0.5、标准差为1.5：
 tensor([[[ 2.5918, -0.9330, -0.5955, -1.0014],
         [-0.1174, -0.7976,  1.8588, -0.7908],
         [ 3.7150,  1.0008,  1.6499,  1.8445]],

        [[ 3.1865,  0.1357,  1.0582,  4.7268],
         [ 1.2922,  1.7455, -0.0355,  0.2595],
         [ 1.0048, -0.0224, -0.6887,  1.9635]]])
均匀分布张量，指定随机序列范围为(-5, 5)：
 tensor([[[-4.8550,  0.4682, -0.7851,  2.8473],
         [ 

In [6]:
# 拷贝自原属性（形状、数据类型）的新张量
y = torch.empty((2, 3, 4))
print(y)
print(f"拷贝随机张量：\n {torch.rand_like(y)}")
print(f"拷贝标准正态分布张量N(0, 1)，即固定随机序列平均值为0、标准差为1：\n {torch.randn_like(y)}")


tensor([[[1.2185e+24, 1.7082e-42, 2.3694e-38, 2.3694e-38],
         [2.3694e-38, 2.3694e-38, 1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00]],

        [[1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00]]])
拷贝随机张量：
 tensor([[[0.4095, 0.6358, 0.9846, 0.6409],
         [0.2873, 0.9538, 0.5871, 0.8436],
         [0.3890, 0.9903, 0.4846, 0.6287]],

        [[0.7800, 0.5466, 0.9359, 0.2345],
         [0.6673, 0.5746, 0.2401, 0.0623],
         [0.3759, 0.7970, 0.0563, 0.1811]]])
拷贝标准正态分布张量N(0, 1)，即固定随机序列平均值为0、标准差为1：
 tensor([[[ 0.7436, -0.6214, -1.1071, -0.5496],
         [ 1.1928,  0.9128, -0.7392, -0.4619],
         [-0.0308, -0.3141,  0.3029, -0.8890]],

        [[-0.3725, -0.1377, -0.7328, -0.5673],
         [-0.4187,  0.5974, -0.4048,  0.8541],
         [-0.9733,  0.1025, -0.2879, -0.3080]]])


### 3.4 序列初始化张量

In [7]:
print(f"等距离序列，[初始值:0, 结束值)及步长:1 \t {torch.arange(1, 11, 2) = }")
print(f"等间隔序列，[初始值, 结束值]及元素个数 \t {torch.linspace(1, 11, 5) = }")
print(f"等距乱序列，[初始值=0, 结束值)及步长=1 \t {torch.randperm(10) = }")


等距离序列，[初始值:0, 结束值)及步长:1 	 torch.arange(1, 11, 2) = tensor([1, 3, 5, 7, 9])
等间隔序列，[初始值, 结束值]及元素个数 	 torch.linspace(1, 11, 5) = tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000])
等距乱序列，[初始值=0, 结束值)及步长=1 	 torch.randperm(10) = tensor([9, 4, 8, 3, 5, 2, 7, 6, 0, 1])


## 4 Tensor 的索引和数据筛选

In [8]:
c = torch.randn(4, 5)
print(c)


tensor([[ 1.0518, -1.3412, -0.3233,  0.7146, -2.3593],
        [-0.6252,  1.6871, -0.4247, -0.6438, -0.9044],
        [ 0.4766,  0.8582, -2.3031,  0.7300,  1.4451],
        [ 0.0917, -0.0381,  0.2955, -0.7857, -0.4877]])


### 4.1 从最左边的维度向右（块、页、行、列）进行索引

![块页行列.png](assets/imgs/块页行列.png)

[CSDN - 关于PyTorch中阶（维度，dim）上的一些个人理解](https://blog.csdn.net/weixin_44820962/article/details/127163440)

In [9]:
print(c[0])
print(c[0, 1])


tensor([ 1.0518, -1.3412, -0.3233,  0.7146, -2.3593])
tensor(-1.3412)


### 4.2 切片通用形式，[初始值:0, 结束值)及步长:1，不同维度用逗号分隔

In [10]:
d = torch.randn(2, 4, 5)
print(d)
print(d[:, 2:4, 3:5])


tensor([[[ 1.2438,  1.1770,  0.6459,  1.0087, -0.5820],
         [-0.5488,  0.9459,  0.7546, -0.7657,  0.1373],
         [ 0.1473,  2.5231, -0.0736, -0.4812,  1.2578],
         [-1.4838,  0.1906,  1.3436,  1.3696, -0.5665]],

        [[ 2.1600, -0.5938, -0.4649,  0.1788, -0.1575],
         [ 0.2622,  0.1103,  1.4622, -1.5443, -0.9607],
         [ 0.2643, -0.0946,  1.0866, -0.9183, -0.0247],
         [ 1.1908, -0.8221, -0.4591,  1.7359,  1.3492]]])
tensor([[[-0.4812,  1.2578],
         [ 1.3696, -0.5665]],

        [[-0.9183, -0.0247],
         [ 1.7359,  1.3492]]])


### 4.3 选取第n维度

In [11]:
print(torch.index_select(d, 1, torch.tensor([0, 2])))


tensor([[[ 1.2438,  1.1770,  0.6459,  1.0087, -0.5820],
         [ 0.1473,  2.5231, -0.0736, -0.4812,  1.2578]],

        [[ 2.1600, -0.5938, -0.4649,  0.1788, -0.1575],
         [ 0.2643, -0.0946,  1.0866, -0.9183, -0.0247]]])



### 4.4 全部选取（一维:，多维...)

In [12]:
print(d[..., 0:3:2, :])


tensor([[[ 1.2438,  1.1770,  0.6459,  1.0087, -0.5820],
         [ 0.1473,  2.5231, -0.0736, -0.4812,  1.2578]],

        [[ 2.1600, -0.5938, -0.4649,  0.1788, -0.1575],
         [ 0.2643, -0.0946,  1.0866, -0.9183, -0.0247]]])


## 5 Tensor 的数学运算

- 标量加法：`add`、`+`
- 标量减法：`sub`、`-`
- 标量乘法：`mul`、`*`
- 标量除法：`div`、`/`
- 标量次方：`pow`、`**`
- 标量开方：`sqrt`

- 矩阵乘法：`matmul`、`@`

- 向下取整：`floor`
- 向上取整：`ceil`
- 四舍五入：`round`
- 去尾取整：`trunc`
- 去头取小：`frac`

In [13]:
e = torch.round(torch.rand(2, 2) * 10)
f = torch.round(torch.rand(2, 2) * 10)
print(e)
print(f)
print(f"标量加法：\n {e + f} \n {e.add(f)}")
print(f"标量减法：\n {e - f} \n {e.sub(f)}")
print(f"标量乘法：\n {e * f} \n {e.mul(f)}")
print(f"标量除法：\n {e / f} \n {e.div(f)}")
print(f"标量次方：\n {e ** f} \n {e.pow(f)}")
print(f"标量开方：\n {e.sqrt()}")


tensor([[5., 2.],
        [9., 9.]])
tensor([[1., 6.],
        [4., 7.]])
标量加法：
 tensor([[ 6.,  8.],
        [13., 16.]]) 
 tensor([[ 6.,  8.],
        [13., 16.]])
标量减法：
 tensor([[ 4., -4.],
        [ 5.,  2.]]) 
 tensor([[ 4., -4.],
        [ 5.,  2.]])
标量乘法：
 tensor([[ 5., 12.],
        [36., 63.]]) 
 tensor([[ 5., 12.],
        [36., 63.]])
标量除法：
 tensor([[5.0000, 0.3333],
        [2.2500, 1.2857]]) 
 tensor([[5.0000, 0.3333],
        [2.2500, 1.2857]])
标量次方：
 tensor([[5.0000e+00, 6.4000e+01],
        [6.5610e+03, 4.7830e+06]]) 
 tensor([[5.0000e+00, 6.4000e+01],
        [6.5610e+03, 4.7830e+06]])
标量开方：
 tensor([[2.2361, 1.4142],
        [3.0000, 3.0000]])


In [14]:
print(e @ f)
print(e.matmul(f))


tensor([[ 13.,  44.],
        [ 45., 117.]])
tensor([[ 13.,  44.],
        [ 45., 117.]])


## 6 Tensor 的统计属性

- 求范数：`norm`

聚合运算（降维）
- 平均值：`mean`
- 求和：`sum`
- 累乘：`prod`
> 注：
> dim 默认按列行聚合，返回标量
> - 0：按列聚合
> - 1：按行聚合

- 最大值：`max`
- 最大值索引：`argmax`
- 最小值：`min`
- 最小值索引：`argmin`
- 第k小的值：`kthvalue`
- 前k小的值：`topk`

In [15]:
g = torch.rand(2, 2)
print(g)

print(f"求和：\n {g.sum()}")
print(f"按列求和：\n {g.sum(0)}")
print(f"按行求和：\n {g.sum(1)}")

print(f"求和：\n {torch.sum(g)}")
print(f"按列求和：\n {torch.sum(g, dim=0)}")
print(f"按行求和：\n {torch.sum(g, dim=1)}")


tensor([[0.0687, 0.0098],
        [0.7245, 0.1637]])
求和：
 0.9666789770126343
按列求和：
 tensor([0.7932, 0.1735])
按行求和：
 tensor([0.0785, 0.8882])
求和：
 0.9666789770126343
按列求和：
 tensor([0.7932, 0.1735])
按行求和：
 tensor([0.0785, 0.8882])


In [16]:
h = torch.trunc(torch.randn(5, 5) * 10)
print(h)

print(f"最大值：\n {h.max()}")
print(f"最大值索引：\n {h.argmax()}")
print(f"每行最大值：\n {h.max(dim=1)}")
print(f"每行最大值索引：\n {h.argmax(dim=1)}")
print(f"每行最大值（取消降维转置）：\n {h.max(dim=1, keepdim=True)}")
print(f"每行最大值索引（取消降维转置）：\n {h.argmax(dim=1, keepdim=True)}")

print(f"最大值：\n {torch.max(h)}")
print(f"最大值索引：\n {torch.argmax(h)}")
print(f"每行最大值：\n {torch.max(h, 1)}")
print(f"每行最大值索引：\n {torch.argmax(h, 1)}")
print(f"每行最大值（取消降维转置）：\n {torch.max(h, 1, True)}")
print(f"每行最大值索引（取消降维转置）：\n {torch.argmax(h, 1, True)}")


tensor([[ -4.,  14.,  -3.,  -1.,   3.],
        [  7., -15.,  13.,  -1., -12.],
        [ -1.,  -3., -10.,  -0.,   9.],
        [ -0.,  -6.,   0.,   6.,   0.],
        [  2.,  -1.,  -2.,  -6.,  15.]])
最大值：
 15.0
最大值索引：
 24
每行最大值：
 torch.return_types.max(
values=tensor([14., 13.,  9.,  6., 15.]),
indices=tensor([1, 2, 4, 3, 4]))
每行最大值索引：
 tensor([1, 2, 4, 3, 4])
每行最大值（取消降维转置）：
 torch.return_types.max(
values=tensor([[14.],
        [13.],
        [ 9.],
        [ 6.],
        [15.]]),
indices=tensor([[1],
        [2],
        [4],
        [3],
        [4]]))
每行最大值索引（取消降维转置）：
 tensor([[1],
        [2],
        [4],
        [3],
        [4]])
最大值：
 15.0
最大值索引：
 24
每行最大值：
 torch.return_types.max(
values=tensor([14., 13.,  9.,  6., 15.]),
indices=tensor([1, 2, 4, 3, 4]))
每行最大值索引：
 tensor([1, 2, 4, 3, 4])
每行最大值（取消降维转置）：
 torch.return_types.max(
values=tensor([[14.],
        [13.],
        [ 9.],
        [ 6.],
        [15.]]),
indices=tensor([[1],
        [2],
        [4],
        [3],
      

In [17]:
print(h)
print(f"按列第2小的值：\n {torch.kthvalue(h, 2, dim=0)}")
print(f"按列前2小的值：\n {torch.topk(h, 2, dim=0, largest=False)}")

print(f"按行第2小的值：\n {torch.kthvalue(h, 2, dim=1)}")
print(f"按行前2小的值：\n {torch.topk(h, 2, largest=False)}")


tensor([[ -4.,  14.,  -3.,  -1.,   3.],
        [  7., -15.,  13.,  -1., -12.],
        [ -1.,  -3., -10.,  -0.,   9.],
        [ -0.,  -6.,   0.,   6.,   0.],
        [  2.,  -1.,  -2.,  -6.,  15.]])
按列第2小的值：
 torch.return_types.kthvalue(
values=tensor([-1., -6., -3., -1.,  0.]),
indices=tensor([2, 3, 0, 0, 3]))
按列前2小的值：
 torch.return_types.topk(
values=tensor([[ -4., -15., -10.,  -6., -12.],
        [ -1.,  -6.,  -3.,  -1.,   0.]]),
indices=tensor([[0, 1, 2, 4, 1],
        [2, 3, 0, 0, 3]]))
按行第2小的值：
 torch.return_types.kthvalue(
values=tensor([ -3., -12.,  -3.,   0.,  -2.]),
indices=tensor([2, 4, 1, 2, 2]))
按行前2小的值：
 torch.return_types.topk(
values=tensor([[ -4.,  -3.],
        [-15., -12.],
        [-10.,  -3.],
        [ -6.,  -0.],
        [ -6.,  -2.]]),
indices=tensor([[0, 2],
        [1, 4],
        [2, 1],
        [1, 0],
        [3, 2]]))
