# Tensor 张量

## 1 深度学习基础概念 - 机器学习的两个基本问题

### 1.1 分类问题

分类问题的目标是预测一个离散的标签或类别。
这些标签通常是有限的，并且代表了不同的类别或组。

### 1.2 回归问题

回归问题的目标是预测一个连续的数值变量。
这些数值可以是无限的，回归模型尝试找到输入变量和连续输出变量之间的关系。


## 2 标量、向量、矩阵、张量

- 标量（Scalar）：0 阶张量
- 向量（Vector）：1 阶张量
- 矩阵（Matrix）：2 阶张量
- 张量（Tensor）：n 阶（Dimensions，维）


## 3 Tensor 的创建

### 3.1 创建特定值张量

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())


2.2.2
True


In [2]:
# 直接赋值初始化
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# 返回a的Tensor类型
print(a.type())
# 返回a的Tensor形状
print(a.shape)
# 创建指定形状的Tensor
b = torch.Tensor(2, 3)
print(b)
print(b.type())


torch.LongTensor
torch.Size([2, 3])
tensor([[-2.9040e-34,  1.8707e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
torch.FloatTensor


### 3.2 创建特殊值张量

In [3]:
print(f"全1张量：\n {torch.ones((2, 3, 4))}")
print(f"全0张量：\n {torch.zeros((2, 3, 4))}")
print(f"单位矩阵：\n {torch.eye(3)}")
print(f"指定大小张量：\n {torch.empty((2, 3, 4))}")
print(f"指定大小和值张量：\n {torch.full((2, 3, 4), 5)}")


全1张量：
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
全0张量：
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
单位矩阵：
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
指定大小张量：
 tensor([[[-2.9493e-34,  1.8707e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
指定大小和值张量：
 tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]])


In [4]:
# 拷贝自原属性（形状、数据类型）的新张量
x = torch.empty((2, 3, 4))
print(x)
print(f"拷贝全1张量：\n {torch.ones_like(x)}")
print(f"拷贝全0张量：\n {torch.zeros_like(x)}")
print(f"拷贝指定大小张量：\n {torch.empty_like(x)}")
print(f"拷贝指定大小和值张量：\n {torch.full_like(x, 5)}")


tensor([[[-2.9494e-34,  1.8707e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
拷贝全1张量：
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
拷贝全0张量：
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
拷贝指定大小张量：
 tensor([[[-2.9048e-34,  1.8707e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
   

### 3.3 随机初始化张量

In [5]:
print(f"随机张量∈(0, 1)：\n {torch.rand((2, 3, 4))}")
print(f"标准正态分布张量N(0, 1)，即固定随机序列平均值为0、标准差为1：\n {torch.randn((2, 3, 4))}")
print(f"正态分布张量，指定随机序列平均值为0.5、标准差为1.5：\n {torch.normal(0.5, 1.5, (2, 3, 4))}")
print(f"均匀分布张量，指定随机序列范围为(-5, 5)：\n {torch.Tensor(2, 3, 4).uniform_(-5, 5)}")


随机张量∈(0, 1)：
 tensor([[[0.7688, 0.1197, 0.1395, 0.0399],
         [0.6709, 0.6557, 0.7611, 0.4114],
         [0.3408, 0.6320, 0.8547, 0.8268]],

        [[0.5782, 0.3011, 0.0477, 0.4260],
         [0.2365, 0.3435, 0.3106, 0.4258],
         [0.6456, 0.1257, 0.3132, 0.4032]]])
标准正态分布张量N(0, 1)，即固定随机序列平均值为0、标准差为1：
 tensor([[[ 2.0059, -0.3452,  0.8091,  2.0749],
         [-2.0739, -0.5483, -0.5627,  0.1265],
         [ 2.2766,  0.8348, -1.7597,  0.2152]],

        [[ 0.4798,  0.4452,  0.3171,  0.7095],
         [ 1.9707, -2.1797, -1.2751,  0.4859],
         [-0.5527,  2.1053,  0.9853,  0.0273]]])
正态分布张量，指定随机序列平均值为0.5、标准差为1.5：
 tensor([[[ 2.3982,  1.0216,  1.0596,  0.2840],
         [-0.4369, -1.6167,  2.6768,  0.3559],
         [-0.8732,  1.2567,  0.1081, -1.8248]],

        [[-1.8359,  0.1405,  2.2148, -0.5638],
         [ 0.4863, -1.7744, -0.2744,  0.6459],
         [ 2.7501,  0.3647,  0.3293,  0.1849]]])
均匀分布张量，指定随机序列范围为(-5, 5)：
 tensor([[[-4.5581,  4.6662,  0.9628,  0.2505],
         [-

In [6]:
# 拷贝自原属性（形状、数据类型）的新张量
y = torch.empty((2, 3, 4))
print(y)
print(f"拷贝随机张量：\n {torch.rand_like(y)}")
print(f"拷贝标准正态分布张量N(0, 1)，即固定随机序列平均值为0、标准差为1：\n {torch.randn_like(y)}")


tensor([[[-2.9042e-34,  1.8707e-42,  2.3694e-38,  2.3694e-38],
         [ 2.3694e-38,  2.3694e-38,  1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]],

        [[ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]]])
拷贝随机张量：
 tensor([[[0.7945, 0.3189, 0.9701, 0.9871],
         [0.4470, 0.3392, 0.0464, 0.6544],
         [0.2936, 0.9403, 0.8561, 0.8331]],

        [[0.7192, 0.8666, 0.6920, 0.6897],
         [0.6838, 0.1659, 0.5712, 0.9034],
         [0.8830, 0.1890, 0.6568, 0.1418]]])
拷贝标准正态分布张量N(0, 1)，即固定随机序列平均值为0、标准差为1：
 tensor([[[-8.9645e-01,  3.7762e-04, -1.6853e-01, -3.3387e-01],
         [ 4.3234e-01,  1.4478e+00, -1.6361e+00,  1.8688e-01],
         [ 1.5955e-01,  1.7617e-01, -2.8403e-01,  3.1612e-01]],

        [[-2.8568e-01, -2.2003e-02, -3.8374e-01,  1.0742e+00],
         [-2.0880e-01, -3.0692e-02, -4.1466e-01,  3.72

### 3.4 序列初始化张量

In [7]:
print(f"等距离序列，[初始值:0, 结束值)及步长:1 \t {torch.arange(1, 11, 2) = }")
print(f"等间隔序列，[初始值, 结束值]及元素个数 \t {torch.linspace(1, 11, 5) = }")
print(f"等距乱序列，[初始值=0, 结束值)及步长=1 \t {torch.randperm(10) = }")


等距离序列，[初始值:0, 结束值)及步长:1 	 torch.arange(1, 11, 2) = tensor([1, 3, 5, 7, 9])
等间隔序列，[初始值, 结束值]及元素个数 	 torch.linspace(1, 11, 5) = tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000])
等距乱序列，[初始值=0, 结束值)及步长=1 	 torch.randperm(10) = tensor([4, 6, 7, 0, 5, 2, 9, 3, 8, 1])


## 4 Tensor 的索引和数据筛选

In [8]:
c = torch.randn(4, 5)
print(c)


tensor([[-0.2922, -1.4149,  0.1245,  0.8448, -0.7111],
        [ 0.2559,  0.4206,  1.4145,  0.0199,  0.9414],
        [ 0.6039,  0.0567, -0.0771,  0.7364,  0.3849],
        [ 1.4509,  0.9842,  0.7542,  0.6087, -1.2715]])


### 4.1 从最左边的维度向右（块、页、行、列）进行索引

![块页行列.png](assets/imgs/块页行列.png)

[CSDN - 关于PyTorch中阶（维度，dim）上的一些个人理解](https://blog.csdn.net/weixin_44820962/article/details/127163440)

In [9]:
print(c[0])
print(c[0, 1])


tensor([-0.2922, -1.4149,  0.1245,  0.8448, -0.7111])
tensor(-1.4149)


### 4.2 切片通用形式，[初始值:0, 结束值)及步长:1，不同维度用逗号分隔

In [10]:
d = torch.randn(2, 4, 5)
print(d)
print(d[:, 2:4, 3:5])


tensor([[[ 0.4498, -0.9076, -1.0529, -1.8473,  0.5475],
         [ 0.1050,  1.5645, -2.6079,  1.7241, -1.5794],
         [-1.3223,  0.6124,  1.8385,  0.6725, -0.8471],
         [ 0.2011,  0.4707, -2.2818,  2.7241,  0.2234]],

        [[-1.4439, -0.9291,  2.0292,  0.5244,  1.0667],
         [-0.6663, -0.0362, -0.4639,  0.0275,  0.2364],
         [ 0.6124,  0.1192, -0.7393,  0.0433,  0.2904],
         [ 0.0121, -0.9580, -0.9038,  0.2003,  0.8168]]])
tensor([[[ 0.6725, -0.8471],
         [ 2.7241,  0.2234]],

        [[ 0.0433,  0.2904],
         [ 0.2003,  0.8168]]])


### 4.3 选取第n维度

In [11]:
print(torch.index_select(d, 1, torch.tensor([0, 2])))


tensor([[[ 0.4498, -0.9076, -1.0529, -1.8473,  0.5475],
         [-1.3223,  0.6124,  1.8385,  0.6725, -0.8471]],

        [[-1.4439, -0.9291,  2.0292,  0.5244,  1.0667],
         [ 0.6124,  0.1192, -0.7393,  0.0433,  0.2904]]])



### 4.4 全部选取（一维:，多维...)

In [12]:
print(d[..., 0:3:2, :])


tensor([[[ 0.4498, -0.9076, -1.0529, -1.8473,  0.5475],
         [-1.3223,  0.6124,  1.8385,  0.6725, -0.8471]],

        [[-1.4439, -0.9291,  2.0292,  0.5244,  1.0667],
         [ 0.6124,  0.1192, -0.7393,  0.0433,  0.2904]]])


## 5 Tensor 的数学运算

- 标量加法：`add`、`+`
- 标量减法：`sub`、`-`
- 标量乘法：`mul`、`*`
- 标量除法：`div`、`/`
- 标量次方：`pow`、`**`
- 标量开方：`sqrt`

- 矩阵乘法：`matmul`、`@`

- 向下取整：`floor`
- 向上取整：`ceil`
- 四舍五入：`round`
- 去尾取整：`trunc`
- 去头取小：`frac`

In [13]:
e = torch.round(torch.rand(2, 2) * 10)
f = torch.round(torch.rand(2, 2) * 10)
print(e)
print(f)
print(f"标量加法：\n {e + f} \n {e.add(f)}")
print(f"标量减法：\n {e - f} \n {e.sub(f)}")
print(f"标量乘法：\n {e * f} \n {e.mul(f)}")
print(f"标量除法：\n {e / f} \n {e.div(f)}")
print(f"标量次方：\n {e ** f} \n {e.pow(f)}")
print(f"标量开方：\n {e.sqrt()}")


tensor([[9., 3.],
        [9., 9.]])
tensor([[0., 1.],
        [7., 3.]])
标量加法：
 tensor([[ 9.,  4.],
        [16., 12.]]) 
 tensor([[ 9.,  4.],
        [16., 12.]])
标量减法：
 tensor([[9., 2.],
        [2., 6.]]) 
 tensor([[9., 2.],
        [2., 6.]])
标量乘法：
 tensor([[ 0.,  3.],
        [63., 27.]]) 
 tensor([[ 0.,  3.],
        [63., 27.]])
标量除法：
 tensor([[   inf, 3.0000],
        [1.2857, 3.0000]]) 
 tensor([[   inf, 3.0000],
        [1.2857, 3.0000]])
标量次方：
 tensor([[1.0000e+00, 3.0000e+00],
        [4.7830e+06, 7.2900e+02]]) 
 tensor([[1.0000e+00, 3.0000e+00],
        [4.7830e+06, 7.2900e+02]])
标量开方：
 tensor([[3.0000, 1.7321],
        [3.0000, 3.0000]])


In [14]:
print(e @ f)
print(e.matmul(f))


tensor([[21., 18.],
        [63., 36.]])
tensor([[21., 18.],
        [63., 36.]])


## 6 Tensor 的统计属性

聚合运算（降维）
- 求范数：`norm`
- 平均值：`mean`
- 求和：`sum`
- 累乘：`prod`
> 注：
> dim 默认按列行聚合，返回标量
> - 0：按列聚合
> - 1：按行聚合

- 最大值：`max`
- 最大值索引：`argmax`
- 最小值：`min`
- 最小值索引：`argmin`
- 第k小的值：`kthvalue`
- 前k小的值：`topk`

In [15]:
g = torch.rand(2, 2)
print(g)

print(f"求和：\n {g.sum()}")
print(f"按列求和：\n {g.sum(0)}")
print(f"按行求和：\n {g.sum(1)}")

print(f"求和：\n {torch.sum(g)}")
print(f"按列求和：\n {torch.sum(g, dim=0)}")
print(f"按行求和：\n {torch.sum(g, dim=1)}")


tensor([[0.4598, 0.6825],
        [0.6619, 0.5100]])
求和：
 2.3142499923706055
按列求和：
 tensor([1.1217, 1.1926])
按行求和：
 tensor([1.1423, 1.1719])
求和：
 2.3142499923706055
按列求和：
 tensor([1.1217, 1.1926])
按行求和：
 tensor([1.1423, 1.1719])


In [16]:
h = torch.trunc(torch.randn(5, 5) * 10)
print(h)

print(f"最大值：\n {h.max()}")
print(f"最大值索引：\n {h.argmax()}")
print(f"每行最大值：\n {h.max(dim=1)}")
print(f"每行最大值索引：\n {h.argmax(dim=1)}")
print(f"每行最大值（取消降维转置）：\n {h.max(dim=1, keepdim=True)}")
print(f"每行最大值索引（取消降维转置）：\n {h.argmax(dim=1, keepdim=True)}")

print(f"最大值：\n {torch.max(h)}")
print(f"最大值索引：\n {torch.argmax(h)}")
print(f"每行最大值：\n {torch.max(h, 1)}")
print(f"每行最大值索引：\n {torch.argmax(h, 1)}")
print(f"每行最大值（取消降维转置）：\n {torch.max(h, 1, True)}")
print(f"每行最大值索引（取消降维转置）：\n {torch.argmax(h, 1, True)}")


tensor([[-14.,  -3.,  19.,   9.,  11.],
        [  2.,   0., -10.,   0.,  -0.],
        [ 10.,  -3.,   9.,   2.,  -0.],
        [  6., -14.,  -4.,   0.,  -1.],
        [  1.,   8.,  17.,  20.,   3.]])
最大值：
 20.0
最大值索引：
 23
每行最大值：
 torch.return_types.max(
values=tensor([19.,  2., 10.,  6., 20.]),
indices=tensor([2, 0, 0, 0, 3]))
每行最大值索引：
 tensor([2, 0, 0, 0, 3])
每行最大值（取消降维转置）：
 torch.return_types.max(
values=tensor([[19.],
        [ 2.],
        [10.],
        [ 6.],
        [20.]]),
indices=tensor([[2],
        [0],
        [0],
        [0],
        [3]]))
每行最大值索引（取消降维转置）：
 tensor([[2],
        [0],
        [0],
        [0],
        [3]])
最大值：
 20.0
最大值索引：
 23
每行最大值：
 torch.return_types.max(
values=tensor([19.,  2., 10.,  6., 20.]),
indices=tensor([2, 0, 0, 0, 3]))
每行最大值索引：
 tensor([2, 0, 0, 0, 3])
每行最大值（取消降维转置）：
 torch.return_types.max(
values=tensor([[19.],
        [ 2.],
        [10.],
        [ 6.],
        [20.]]),
indices=tensor([[2],
        [0],
        [0],
        [0],
      

In [17]:
print(h)
print(f"按列第2小的值：\n {torch.kthvalue(h, 2, dim=0)}")
print(f"按列前2小的值：\n {torch.topk(h, 2, dim=0, largest=False)}")

print(f"按行第2小的值：\n {torch.kthvalue(h, 2, dim=1)}")
print(f"按行前2小的值：\n {torch.topk(h, 2, largest=False)}")


tensor([[-14.,  -3.,  19.,   9.,  11.],
        [  2.,   0., -10.,   0.,  -0.],
        [ 10.,  -3.,   9.,   2.,  -0.],
        [  6., -14.,  -4.,   0.,  -1.],
        [  1.,   8.,  17.,  20.,   3.]])
按列第2小的值：
 torch.return_types.kthvalue(
values=tensor([ 1., -3., -4.,  0., -0.]),
indices=tensor([4, 2, 3, 3, 2]))
按列前2小的值：
 torch.return_types.topk(
values=tensor([[-14., -14., -10.,   0.,  -1.],
        [  1.,  -3.,  -4.,   0.,  -0.]]),
indices=tensor([[0, 3, 1, 1, 3],
        [4, 0, 3, 3, 1]]))
按行第2小的值：
 torch.return_types.kthvalue(
values=tensor([-3.,  0., -0., -4.,  3.]),
indices=tensor([1, 3, 4, 2, 4]))
按行前2小的值：
 torch.return_types.topk(
values=tensor([[-14.,  -3.],
        [-10.,   0.],
        [ -3.,  -0.],
        [-14.,  -4.],
        [  1.,   3.]]),
indices=tensor([[0, 1],
        [2, 1],
        [1, 4],
        [1, 2],
        [0, 4]]))


## 7 【拓展】 Norm 范数

设二维范数向量 $v = (x, y)$，则有：

- $L_1$ 范数：$||v||_1 = ||(x, y)||_1 = |x| + |y| = (|x|^1, |y|^1)^{\frac{1}{1}}$
- $L_2$ 范数：$||v||_2 = ||(x, y)||_2 = \sqrt{|x|^2 + |y|^2} = (|x|^2, |y|^2)^{\frac{1}{2}}$
- $L_p$ 范数：$||v||_p = ||(x, y)||_p = \sqrt[p]{|x|^p + |y|^p} = (|x|^p, |y|^p)^{\frac{1}{p}}$
- $L_∞$ 范数：$||v||_\infty = ||(x, y)||_\infty = \max(|x|, |y|)$

---

设n维范数向量 $v = (x_1, x_2, ..., x_n)$，则有：

- $L_1$ 范数：$||v||_1 = \sum_{i=1}^n |x_i|$
- $L_2$ 范数：$||v||_2 = \sqrt{\sum_{i=1}^n |x_i|^2}$
- $L_p$ 范数：$||v||_p = \sqrt[p]{\sum_{i=1}^n |x_i|^p}$
- $L_∞$ 范数：$||v||_\infty = \max_{i=1}^n |x_i|$
